spring.application.name=rentar
spring.datasource.url=jdbc:mysql://localhost:3306/rentar
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true

# Configuracion SQL inicial del TP
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=false
spring.jpa.hibernate.ddl-auto=validate

# Habilita la interfaz GraphiQL para probar las consultas GraphQL
spring.graphql.graphiql.enabled=true